[package]
name = "ci-utils"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic-prost-build = { version = "*" }
reqwest = { version = "*", features = ["blocking"] }
